### ISSUE TITLE
Question: how to print to screen (text)?

### ISSUE THREAD

**Issue by ghost** [limine-bootloader/limine-rust-barebones#12]
Sorry that I haven't understood it yet. Is that right?:
1. The easiest/best way to write on the screen is flanterm
2. Either you integrate the flanterm library yourself in rust or you use the flanterm rust bindings.
3. There is currently no code in rust that uses flanterm and limine
4. This solution should be portable
Is there any flow chart or something? Or a c code example?
As I understood, the process is as follows:
- Find out the position of the framebuffer using a limine function
- Integrate flanterm in whatever way you like so that it doesn't need std.
- Use flanterm, but how does that work?

Unfortunately, the documentation on doc.rs/flanterm_bindings is not explained and only contains the names of the variables and functions. The example project from flanterm rust bindings, which should work, does not work because unfortunately the Cargo.toml configuration was not published and all attempts to reconstruct it have failed.
Is there any other documentation?
What options are there?
Thank you very much for an answer!

**Comment by lylythechosenone** [comment]
See: https://github.com/mintsuki/flanterm?tab=readme-ov-file#quick-usage

You can do exactly this with `flanterm_bindings`. The types and functions have exactly the same names. You can use the framebuffer request to get a framebuffer.

I got all of that from a cursory Google search, which you should have done rather than asking on the *wrong repository*. I already told you that this is not the correct place. Next time, please ask in the places I already gave you: [the osdev discord](https://discord.gg/osdev), [the limine discord](https://discord.gg/QEeZMz4), [the flanterm repository](https://github.com/mintsuki/flanterm), or even [Google](https://google.com).

**Comment by ghost** [comment]
a last question. why this repo is the wrong place to ask? A simple print-to-screen-project is something this you can use the knownlage of this repo for, if i not understand it wrong.. why asking anywhere but not here?https://docs.github.com/de/site-policy/github-terms/github-community-guidelines In the first subentry there is standing helpfull information PS: a "simple google search" is not enought. _it can't be good to develop opensource software inside of discord, not everybody can read the conversation and discord has to many privacy issues._

**Comment by lylythechosenone** [comment]
> it can't be good to develop opensource software inside of discord

That's why I provided another repository, the flanterm one.
> A simple print-to-screen-project is something this you can use the knownlage of this repo for, if i not understand it wrong

Issues on this repo are to discuss the code within this repo, not to ask general OSDev questions.
